baseURL = "https://outin.space"

title = "out in space"
author = "Nicholas Wilson"
languageCode = "en-us"
copyright = "Copyright 2020, Nicholas Wilson"
defaultContentLanguage = "en"

theme = "hugo-bearblog"


paginate = 2
canonifyURLs = false
summaryLength = 40
rssLimit = 100
enableEmoji = true
enableRobotsTXT = true
pluralizelisttitles = false

[permalinks]
posts = "/:filename"

# [params]
# mainSections = ["posts"]
# copyrightYear = 2020
# # Go Reference time: Mon Jan 2 15:04:05 MST 2006
# dateFormat = "Jan 2, 2006"
# highlight = "dark"


[outputs]
home = ["HTML", "ATOM"]
section = ["HTML"]
taxonomy = ["HTML"]
taxonomyTerm = ["HTML"]

[outputFormats]
[outputFormats.ATOM]
name = "ATOM"
baseName = "feed"
mediaType = "application/atom+xml"

[mediaTypes]
[mediaTypes."application/atom+xml"]
suffixes = ["atom"]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = false
strikethrough = false
table = true
taskList = false
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
attribute = false
[markup.highlight]
codeFences = true
noClasses = false
tabWidth = 2
# lineNos = true
# lineNumbersInTable = false

[menu]
[[menu.main]]
url = "/posts/"
name = "Posts"
weight = 1

# [[menu.main]]
# url = "/posts/"
# name = "Theology"
# weight = 2

# [[menu.foot]]
# url = "/posts/"
# name = "Posts"
# weight = 1

# [[menu.foot]]
# url = "/about/"
# name = "About"
# weight = 2

# [[menu.foot]]
# url = "/contact/"
# name = "Contact"
# weight = 3


[languages]
[languages."en"]
weight = 1
languageName = "English"
